bitcrowd/sshkit.ex

.editorconfig

Adds a basic `.editorconfig` file ensuring some basic formatting rules are followed.

[#19] Add `.editorconfig`

---

.gitignore
.travis.yml
README.md
mix.exs

Adds a `.travis.yml` running:
- `mix credo --strict`
- `mix test`, and
- `mix inch.report` (after the tests)
Pull-request to add `bitcrowd/sshkit.ex` to [Inch CI](https://inch-ci.org/github/bitcrowd/sshkit.ex) is here: https://github.com/rrrene/inch_ex/pull/46

[#16] Set up continuous integration checks

---

lib/sshkit/scp/download.ex

Fix for https://github.com/bitcrowd/sshkit.ex/issues/27
Removes the checks for the sentinel bytes that (I think) only belong in upload.

Fix SCP download

---

lib/sshkit/scp/upload.ex

Fixes the pattern match so that an `:eof` is correctly returned for larger file uploads.
Fixes #30

Allow upload of larger files

---

CHNAGELOG.md
lib/sshkit/context.ex
test/sshkit/context_test.exs
test/sshkit_functional_test.exs

Fixes a bug that prevented `SSHKit.env` from working.
Also added documentation and unit tests; un-skipped the corresponding functional test.
---

[#35] SSHKit.env not working as expected

---

lib/sshkit/context.ex

There was an error here @tessi… there should not be a space in between the three backticks. I only had those in there because they we're inside a GitHub comment code block and they would've broken the formatting otherwise. Sorry for that. I should've made that more obvious.

Fix code block in SSHKit.Context docstring

---

README.md
lib/sshkit.ex

Added documentation for our main DSL
`mix inch --pedantic` now outputs:
```
┃  B  →  SSHKit.host/1
┃  B  →  SSHKit.user/2
┃  B  →  SSHKit.SCP.download/4
┃  B  →  SSHKit.SSH.connect/2
┃  B  →  SSHKit.SCP.upload/4
┃  B  →  SSHKit.SSH.close/1
┃  B  →  SSHKit.SSH.run/3
┃  B  →  SSHKit.context/1
┃  B  →  SSHKit.group/2
┃  B  →  SSHKit.umask/2
┃  B  →  SSHKit.host/2
┃  B  →  SSHKit.path/2
┃  B  →  SSHKit.env/2
┃  B  →  SSHKit.run/2
You might want to look at these files:
┃ /lib/sshkit/host.ex
┃ /lib/sshkit/ssh.ex
┃ /lib/sshkit/scp.ex
┃ /lib/sshkit.ex
Grade distribution (undocumented, C, B, A):  ▁  ▁ █ ▃
```
---

[#46] Add documentation for the basic SSHKit DSL

---

lib/sshkit/context.ex
lib/sshkit/utils.ex
test/sshkit/ssh_functional_test.exs
test/sshkit_functional_test.exs
test/support/docker/Dockerfile

Update the functional tests to allow the test/login user to run `sudo` in order to switch user/group.
TODOs:

[#36] SSHKit.user errors because sudo is missing

---

test/sshkit_functional_test.exs
test/support/docker/Dockerfile

- Enable `SSHKit.group/2` test and run a command in a specific group
- Allow users in the "passwordless-sudoers" group to run commands as any
user and - now also - in any group
- for background information, check out: `man sudoers`
- or (DigitalOcean Tutorial) https://goo.gl/ITWnoC

[#37] SSHKit.group errors because sudo is missing

---

test/sshkit_functional_test.exs

When a test command is expected to be successful, but instead does not exit with 0, customize the failure message to print the command's stderr output.
Also, consistently perform this check before asserting anything about the commands standard output.
This way, it is more quickly and clearly visible why a command failed, because commands that exit with non-zero exit code usually print the reason to stderr.

Better test failure messages

---

test/sshkit_functional_test.exs
test/support/functional_case.ex
test/support/functional_case_helpers.ex

Add a bang `!` to the functional helpers, to show they'll raise an exception if anything goes wrong (they're using the Docker helpers underneath).
This is based on #55 & #56. If these are okay/merged, then only the changes in c1d9c7a are really relevant to this PR.

Add bang to helper functions

---

lib/sshkit/ssh.ex

This is just a tiny refactoring which makes `SSHKit.SSH.run/3` more readable by using the [`with`](https://elixir-lang.org/getting-started/mix-otp/docs-tests-and-with.html#with) construct introduced in Elixir 1.2.

Use `with` over nested `case` calls

---

CHANGELOG.md
lib/sshkit/ssh.ex
lib/sshkit/ssh/connection.ex
test/sshkit/ssh_test.exs

This extends SSHKit.SSH with connect/3 which accepts a function that is
called with the connection. The connection is automatically closed after
the function returned, no matter if it errored or not.
Also: this introduces a new option - "ssh_modules" for
SSHKit.SSH.connect that allows to use own implementations for the
underlying Erlang modules. This can be used for unit testing SSHKit.
This is supposed to close #72 
---

[#72] Allow SSH.connect to receive a lambda where the connection is only open within the lambda

---

lib/sshkit.ex
test/sshkit/sshkit_test.exs

Proposed change for #60 
Adds shared option support during `Context` creation. This will retain any host options already specified, and additionally merge in all shared options to each host in the list. In the case that host option and shared option contain the same key, the host-specific option is retained.
---

Add shared options support to SSHKit.context

---

lib/sshkit/ssh.ex
lib/sshkit/ssh/channel.ex
test/sshkit/ssh_test.exs

This adds some unit test for the public api of `SSHKit.SSH` as specified in #74.
I for now only tested certain limited scenarios of `run/3`, since anything else would require a deeper dive into the internals of `SSH.Channel` *(or an infinite loop 🙈 )*.
I would prefer to first unit test both, `Channel` and `Connection` before getting back to it, as I for now don't have the domain knowledge of both.
As unit tests are blazing fast in Elixir *(plus can be run in parallel)*, I think it makes sense to have all modules unittested anyways.
---

[#74] Add unit tests for the SSH module

---

test/sshkit/scp_functional_test.exs
test/sshkit/ssh_functional_test.exs

This adds another small functional test for SSH.connect. It does the
same as the existing one but utilizes a lambda function for this.
---

[#76] Add functional tests for SSH.connect with lambda functions

---

CHANGELOG.md
lib/sshkit/ssh/channel.ex
lib/sshkit/ssh/connection.ex
lib/sshkit/ssh/dry_run/ssh.ex
lib/sshkit/ssh/dry_run/ssh_connection.ex
test/sshkit/ssh_test.exs
test/sshkit_functional_test.exs

Adds an option `:dry_run` which  lets sshkit log commands, instead of actually executing them on a remote host.
---

[#68] Allow dry-run

---

CHANGELOG.md
lib/sshkit/scp/upload.ex
test/support/functional_assertion_helpers.ex

This breaks compatibility with Elixir 1.2. Shouldn't be an issue given `mix.exs` calls out a minimum of 1.3 already.

Update deprecated String methods for Elixir 1.5.

---

test/test_helper.exs

Allow running non-functional tests without requiring Docker.
In particular, the following will no longer exit with an error if you're not running Docker:
```shell
mix test --exclude functional
```
The following will:
```shell
mix test --exclude functional --include functional
```
---

Allow running non functional tests without docker

---

test/support/docker/Dockerfile

Upgrade the Docker image used for functional testing from `alpine:3.5` to `alpine:3.7`.
---

Upgrade Alpine Linux Docker image

---

lib/sshkit.ex
test/sshkit/context_test.exs
test/sshkit/sshkit_test.exs

Fixes #103.
This test for `Context` was actually testing the SSHKit module and should therefore go into `sshkit_test.exs`. Plus, it did not need to `build` the context, just test the modified context only contains the last env provided to `SSHKit.env/2`.
PS: Trying to create smaller PRs @tessi 😃 
---

[#103] Move SSHKit unit test into correct place

---

CHANGELOG.md

Add a bit of background for dropping the "dry-run" feature to the `CHANGELOG.md` like we discussed today.
The changelog previously stated that we might re-introduce the feature again later, but after discussing it, it seems more appropriate for applications using SSHKit to implement such a feature if they need it.
Closes #100.

[#100] Drop "dry-run" feature

---

.travis.yml

Seems like we no longer need the manual update and can save some time. I've left the commented-out config lines in the file and added a link to the documentation though, in case something crops up again.
Updating apt caches and `docker-ce` takes around 13 s on each Travis CI job. We've added the `before_install` hook in the past because we ran into issues when running tests on Travis CI.

Disable Docker update on Travis CI

---

test/sshkit/scp_functional_test.exs
test/sshkit_functional_test.exs
test/support/functional_assertion_helpers.ex

These tests are currently not run in concurrently with other tests. Both already use temp directories with randomly generated names for testing everything which touches the local system (downloads from a container).
However, to fully isolate them, we also need to avoid things like `File.cd!` which changes the working directory of all (test) processes and can cause parallel tests to fail.
Once they are made fully isolated, there is no need to set `async` to `false` anymore.
✅
Reported times for `mix test --only functional` showed a reduction from 35 s to 25 s on my machine, from 55 s to 39 s on Travis CI, when using `async: true`. Roughly a 28-30% improvement
The current assumption in our functional tests is that they take care to create temp directories whenever they wish to touch the …

Make functional tests run faster

---

test/sshkit/scp_functional_test.exs
test/sshkit/ssh_functional_test.exs
test/sshkit_functional_test.exs
test/support/functional_case.ex

Change `:boot` tag format & allow overriding host options via the tag:
```
@tag boot: <number>
@tag boot: [<options>, ...]
@tag boot: [[user: "tester", password: "secret"]]
```
Additionally, apply common defaults used for testing to all hosts, i.e. the `:silently_accept_hosts` and `:timeout` options.
The returned host maps are now proper structs with fields that are compatible with `SSHKit.host/1`. This means we can pass them to `SSHKit.context` directly.
At the moment, we are not using the SSH keys at all. When we use them, we should generate them selectively for those tests that require it.
This carves another ~22% off of the overall test time. (Locally tests now run in ~17 s while they took 35 s before I started improving the functional tests.)

Improve functional tests (part I)

---

CHANGELOG.md
lib/sshkit/context.ex
test/sshkit/context_test.exs
test/sshkit_functional_test.exs
test/support/functional_assertion_helpers.ex
test/support/functional_case_helpers.ex

* Add test case using a context with all of
* `:user`,
* `:group`,
* `:umask`,
* `:path` and
* `:env`.
* Fix unexpected behavior regarding environment variables in such cases.
> At the moment we're not testing combinations of different SSHKit options. I would therefore like to see functional test cases covering these more complex interactions of SSHKit path, user, group, umask and env.
— see https://github.com/bitcrowd/sshkit.ex/issues/115

[#115] Test more complex combinations of SSHKit context options

---

CHANGELOG.md
lib/sshkit/ssh/channel.ex
test/sshkit/ssh/channel_test.exs
test/support/mocks.ex

Added ptty allocation method for channel
Implementation of http://erlang.org/doc/man/ssh_connection.html#ptty_alloc-4
Some network devices have ssh server which doesn't provide ptty automatically, and we need to request this manually.

PTTY allocation

---

README.md

A small update to the README:
1. Slightly more structured/consistent release instructions
2. Add a nod to the great capistrano/sshkit

Update README: Tweaks to release instructions and nod to capistrano/sshkit and labzero/bootleg

---

CHANGELOG.md
lib/sshkit.ex
lib/sshkit/scp.ex
lib/sshkit/scp/command.ex
lib/sshkit/scp/download.ex
lib/sshkit/scp/upload.ex
test/sshkit/scp/upload_test.exs
test/sshkit_functional_test.exs

Alternative for #139 
* Allow `scp` commands to be customized/mapped
* Use mapping to apply SSHKit context to `scp` commands
Addresses #121:
> ### Expected behavior
>
> The `SSHKit.dowload/3` and `upload/3` functions should respect the context options `path`, `user`, `group`, `env` & `umask` like `SSHKit.run/2` does.
>
> ### Actual Behavior
>
> The `SSHKit.download/3` and `upload/3` functions are not yet fully context-aware. They only take the context `path` into account.

[#121] Context-aware SSHKit downloads & uploads (B)

---

README.md

The link referencing the Elixir guide on writing documentation was not working any longer so it's updated to the new location of the referenced page.

Fix broken "writing docs" link

---

README.md
lib/sshkit.ex

The return values of `SSHKit.run` and `SSHKit.upload` in parts of the documentation were still using a draft version from the initial README-driven development phase 🙄 😇 This updates the examples so they match the actual behavior ✌️

Update return values in documentation

---

.travis.yml
CHANGELOG.md
lib/sshkit/scp/command.ex

Address #147: Fix a deprecation due to `Enum.into/3` a non-empty list.

[#147] Fix deprecation warning in Elixir 1.8

---

CHANGELOG.md
lib/sshkit/ssh/channel.ex
test/sshkit/ssh/channel_functional_test.exs
test/sshkit/ssh/channel_test.exs
test/support/docker/Dockerfile
test/support/mocks.ex

Exposes `:ssh_connection.subsystem/4` in SSHKit.
This is a followup on #137, I can't (or don't know how to) actually attach these changes to the same issue besides mentioning it.
Tests are written and feedback in that PR is applied. Please double check if what I'm doing in the unit tests makes sense because this was my first time working with Mox and it was somewhat trial and error to get there 😄 
The unit test for the timeout feels a bit silly, I'm not sure if it adds a lot. I thought about adding it as a functional test by adding a clause in the subsystem that sleeps for a bit, but I doubt if the added complexity to the currently pretty straightforward test subsystem is worth it.
I'm using the Netconf driver that @derekkraan wrote, and activating the Netconf subsystem is required for …

Expose `:ssh_connection.subsystem/4`.

---

.github/workflows/ci.yml

The old setup-elixir build is unmaintained and does not work anymore (see #161) .
https://github.com/actions/setup-elixir#setup-elixir
The new official one is:
https://github.com/erlef/setup-beam
from the Erlang Ecosystem Foundation

Switch to actions/setup-elixir@v1

---

lib/sshkit/scp/upload.ex
test/sshkit/scp/upload_test.exs
test/sshkit/scp_functional_test.exs
test/sshkit_functional_test.exs

In the context of #160 we debugged a bit into certain cases, when we have files that do not exists or when we have no permission. 
We have a very first draft in handling those cases.
Probably this is also liked to #62. 
We added some clauses that treat output on `stderr` or warnings that we do not recognize to be `fatal` and lead to error output.

Better error handling for scp uploads
