mix.exs

SSHKit will be/is more than just a wrapper around the underlying Erlang
ssh libraries, supporting SCP and ultimately implementing a DSL for
specifying how to run tasks on remote machines.

Update package description

---

mix.exs
mix.lock

Adds [credo](https://github.com/rrrene/credo) to the project `:dev`/`:test` dependencies.
Does not yet enforce code consistency or remove existing offenses. To be done in the scope of #16.

[#15] Add code style checks

---

README.md

Here's a first step towards making the README a little more informative and welcoming.

[#14] Update README

---

lib/sshkit/ssh/channel.ex
lib/sshkit/ssh/connection.ex
lib/sshkit/utils.ex
test/sshkit/context_test.exs
test/sshkit/ssh_test.exs
test/sshkit/utils_test.exs
test/sshkit_test.exs

Adapted from @svoynow's stab at this (see PR #12). Also converts binaries in nested lists and keywords.

[#9] Convert binaries to charlists for Erlang

---

lib/sshkit/scp/download.ex

A bit of then unused code was left in #28 which is removed here.
Also, this contains:
1. A small fix in the else branch of the `Download.next` function
2. Removes unused `warning` and `fatal` functions
3. Removes unused `errs` list

Clean up unused code in SCP downloads, small fix

---

.github/PULL_REQUEST_TEMPLATE.md
CHNAGELOG.md
README.md
lib/sshkit.ex
lib/sshkit/context.ex
test/sshkit_functional_test.exs

cc @brienw, thanks a lot for the great suggestion!

[#33] Rename `SSHKit.pwd` to `SSHKit.path`

---

.credo.exs
.travis.yml
lib/sshkit.ex
lib/sshkit/context.ex
lib/sshkit/host.ex
lib/sshkit/scp/download.ex
lib/sshkit/scp/upload.ex
lib/sshkit/ssh.ex
lib/sshkit/ssh/channel.ex
lib/sshkit/ssh/connection.ex
lib/sshkit/utils.ex
mix.lock
test/sshkit/utils_test.exs
test/sshkit_functional_test.exs
test/support/docker.ex
test/support/functional_case.ex
test/support/functional_case_helpers.ex

* run credo on ci
* update credo from 0.7.0 to 0.7.3
* fix credo complaints
* some refactorings in SCP upload/download
---

[#44] Add credo check on travis runs

---

README.md
lib/sshkit.ex
lib/sshkit/context.ex
lib/sshkit/host.ex
lib/sshkit/ssh/channel.ex
lib/sshkit/ssh/connection.ex

Please see the commit messages for details on changes.
**TL;DR summary**
- Updates the README notes on testing
- Updates the README to provide a quick overview of the general module structure
- Fixes module documentation and examples
- Adds module documentation for `SSHKit.SSH.Connection` and `SSHKit.SSH.Channel`
- Inserts links and additional cross-references between modules
- Smaller formatting and wording updates
**Once this is merged**, I believe https://github.com/bitcrowd/sshkit.ex/issues/14 can be closed.

Update readme and documentation

---

lib/sshkit/ssh/connection.ex
test/sshkit/ssh_functional_test.exs

Proposed fix for #69 
Please replace this with a description of what you did.
Ideally, reference the issue your PR originated from and make sure to check the following list.
---

Return error if host is nil

---

CHANGELOG.md
README.md

Please replace this with a description of what you did.
Ideally, reference the issue your PR originated from and make sure to check the following list.
---

[#83] Prepare for 0.0.3

---

.travis.yml

This enables testing with Elixir 1.5 in CI.
*(super simple, I can also merge it myself)*
---

[#86] Test with Elixir 1.5 in CI

---

mix.lock

Upgrade ex_doc from 0.16.1 to 0.18.3

---

CHANGELOG.md
lib/sshkit/context.ex
test/sshkit/context_test.exs

Handle empty map case for Context.env

---

.github/ISSUE_TEMPLATE.md

Adds an issue template which asks for information which will hopefully help us in reproducing/identifying problems and responding to issues more quickly.

[#104] Add issue template

---

.github/PULL_REQUEST_TEMPLATE.md

Update the pull request template. Not sure if it's maybe too daunting/too much text…
Got inspiration here: https://www.talater.com/open-source-templates/#/
Let me know what you think.

[#106] Update pull request template

---

lib/sshkit.ex
test/sshkit/sshkit_test.exs

**Fixes #109 (part 1). Adds tests for `SSHKit` functions.**
For your review, please go through commit by commit.
It seemed impractical to open a separate PR for each of these.
Each individual commit should be small and focused enough to be easy to grok.
If you don't like some of them it's simple enough to kick out separate commits.
---

[#109] Part I: Improve unit tests for SSHKit

---

CHANGELOG.md
lib/sshkit/context.ex
test/sshkit/context_test.exs

**Fixes #109 (part 2). Adds tests for `SSHKit.Context` functions.**
---

[#109] Part II: Improve unit tests for Context

---

test/fixtures/local.txt
test/fixtures/local_dir/other.txt
test/fixtures/local_workspace/dir/test.file
test/fixtures/local_workspace/local_file.txt
test/sshkit/scp_functional_test.exs
test/sshkit_functional_test.exs
test/support/docker/fixtures/file.txt
test/support/docker/fixtures/remote.txt
test/support/docker/fixtures/remote_dir/other.txt
test/support/docker/fixtures/some_dir/another_file.txt

Use - hopefully - more obvious naming and more helpful content for fixture files. Remove extra, unnecessary level of nesting from local fixture directory.

Slightly reorganize fixture files

---

test/sshkit_functional_test.exs

Group together the functional tests for `SSHKit.run/2` the same way we grouped those for `SSHKit.upload/3` and `SSHKit.download/3`.
It seems like these tests should be grouped consistently. Also, the updated version shows somewhat more clearly that we might want to add tests for `upload` and `download` with contexts that have `path`, `env` or other options set.

Improve functional tests (part II)

---

CHANGELOG.md
README.md

* added documentation in README.me about the release process
* to fix #133 -- we don't want to search in my zsh-history for how to release, but make sure everyone can release without googling :)
* documentation (README.md) only

[#133] Add documentation on how to release this

---

lib/sshkit.ex

Fix a number of smaller wording issues in the `SSHKit.download/3` documentation.
A few (copy-paste) issues have somehow managed to sneak into the documentation, which are fixed in this PR.

Fix wording in the `SSHKit.download/3` docs

---

README.md
mix.exs
mix.lock

Release 0.2.0 (updated)

---

CHANGELOG.md
mix.exs

Prepare a new release. Please see the diff/changelog for details ✌️

Release 0.3.0

---

.herodot.yml

The repo has been archived and I believe nobody is using it anymore: https://github.com/bitcrowd/herodot
🧹

Remove .herodot.yml

---

CHANGELOG.md
lib/sshkit/ssh/channel.ex
test/sshkit/ssh/channel_test.exs
test/support/mocks.ex

Implementation of Erlang Connection [shell](https://www.erlang.org/doc/man/ssh_connection.html#shell-2)
We use SSHKit to connect to Network devices and in most cases `ptty` is sufficient, but for some devices we actually need to open a shell to execute commands. Without this feature we have to call the Erlang ssh_connection for shell implementation.

Add SSH Connection shell
